---
name: build-main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: Install Node.js dependencies
        run: yarn

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: feed-github
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/82425418?s=200&v=4
          SLACK_TITLE: 'cld-cli to dev :rocket:'
          SLACK_USERNAME: cld-cli-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify failures
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_LINK_NAMES: true
          SLACK_MESSAGE:
            # prettier-ignore
            "hey @${{ github.actor }}, @mark, sorry to let you know you broke the build"
          SLACK_CHANNEL: feed-github
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/82425418?s=200&v=4
          SLACK_TITLE: 'Failed: cld-cli to dev :fire:'
          SLACK_USERNAME: cld-cli-bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
